// Copyright (c) 2025, the R8 project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

package com.android.tools.r8.assistant.runtime;

import com.android.tools.r8.keepanno.annotations.KeepForApi;

@KeepForApi
public enum ReflectiveEventType {
  CLASS_NEW_INSTANCE,
  CLASS_GET_DECLARED_METHOD,
  CLASS_GET_DECLARED_METHODS,
  CLASS_GET_DECLARED_FIELD,
  CLASS_GET_DECLARED_FIELDS,
  CLASS_GET_DECLARED_CONSTRUCTOR,
  CLASS_GET_DECLARED_CONSTRUCTORS,
  CLASS_GET_METHOD,
  CLASS_GET_METHODS,
  CLASS_GET_FIELD,
  CLASS_GET_FIELDS,
  CLASS_GET_CONSTRUCTOR,
  CLASS_GET_CONSTRUCTORS,
  CLASS_GET_NAME,
  CLASS_FOR_NAME,
  CLASS_GET_COMPONENT_TYPE,
  CLASS_GET_PACKAGE,
  CLASS_IS_ASSIGNABLE_FROM,
  CLASS_GET_SUPERCLASS,
  CLASS_AS_SUBCLASS,
  CLASS_IS_INSTANCE,
  CLASS_CAST,
  CLASS_FLAG,
  ATOMIC_FIELD_UPDATER_NEW_UPDATER,
  SERVICE_LOADER_LOAD,
  PROXY_NEW_PROXY_INSTANCE;
}
